# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/129If-m_44JWLjrY9B2xETfMVH1Vf2Kf1
"""

# 在Colab中使用LangChain和千问搭建个人知识库问答工具

## 环境准备与依赖安装
#首先安装所需的库，并确保使用GPU加速# 检查是否使用GPU
import torch
print("是否使用GPU:", torch.cuda.is_available())
print("GPU型号:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "无GPU")

# 安装依赖库
!pip install -q langchain python-dotenv pypdf sentence-transformers chromadb transformers accelerate bitsandbytes gradio
## 挂载Google Drive（可选，用于保存数据）

#如果需要持久化存储文档和向量数据库，可以挂载Google Drivefrom google.colab import drive

# 创建工作目录
import os
work_dir = "/content/drive/MyDrive/qwen_rag1"
if not os.path.exists(work_dir):
    os.makedirs(work_dir)
os.chdir(work_dir)
print("当前工作目录:", os.getcwd())

pip install langchain_community

## 实现RAG应用核心代码import os
import torch
from langchain.document_loaders import PyPDFLoader, TextLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import Chroma
from langchain.chains import RetrievalQA
from langchain.prompts import PromptTemplate
from langchain.llms import HuggingFacePipeline
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline, BitsAndBytesConfig
from google.colab import files

pip install transformers_stream_generator

# 卸载当前版本
!pip uninstall -y chromadb

# 安装稳定版本（推荐 0.4.15 或 0.4.22）
!pip install chromadb==0.4.15

import os
import torch
import shutil
from langchain.document_loaders import PyPDFLoader, TextLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import FAISS  # 改用FAISS
from langchain.chains import RetrievalQA
from langchain.prompts import PromptTemplate
from langchain.llms import HuggingFacePipeline
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline, BitsAndBytesConfig
from google.colab import files, drive

# 安装FAISS的CPU版本（适合Colab环境）
!pip install faiss-cpu

# 安装FAISS的GPU版本（需要CUDA支持）
!pip install faiss-gpu

# 4. 核心类实现（使用FAISS）
class QwenFAISSKnowledgeBase:
    def __init__(self, persist_directory="./qwen_faiss_db"):
        """初始化基于千问和FAISS的知识库"""
        self.persist_directory = persist_directory
        self.vector_db = None
        self.qa_chain = None
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        print(f"使用设备: {self.device}")

        # 初始化中文Embedding模型
        self.embeddings = HuggingFaceEmbeddings(
            model_name="BAAI/bge-small-zh-v1.5",
            model_kwargs={'device': self.device},
            encode_kwargs={'normalize_embeddings': True}
        )

        # 尝试加载已存在的FAISS数据库
        self._load_existing_db()

    def _load_existing_db(self):
        """加载已存在的FAISS数据库"""
        if os.path.exists(self.persist_directory):
            try:
                print("加载已存在的知识库...")
                self.vector_db = FAISS.load_local(
                    self.persist_directory,
                    self.embeddings,
                    allow_dangerous_deserialization=True
                )
                # 测试加载的数据库是否有效
                test_docs = self.vector_db.similarity_search("测试查询")
                if test_docs:
                    self._init_qa_chain()
                    print("知识库加载成功")
                else:
                    print("知识库为空，将重新创建")
                    shutil.rmtree(self.persist_directory)
                    self.vector_db = None
            except Exception as e:
                print(f"加载知识库失败: {e}，将重新创建")
                shutil.rmtree(self.persist_directory)
                self.vector_db = None

    def upload_documents(self):
        """上传文档并处理"""
        print("请上传文档（支持PDF和TXT格式）：")
        uploaded = files.upload()

        if not uploaded:
            print("未上传任何文档")
            return

        # 创建documents目录
        if not os.path.exists("documents"):
            os.makedirs("documents")

        # 保存上传的文件
        file_paths = []
        for filename, content in uploaded.items():
            file_path = f"documents/{filename}"
            with open(file_path, "wb") as f:
                f.write(content)
            file_paths.append(file_path)
            print(f"已保存文件: {file_path}")

        self.load_documents(file_paths)

    def load_documents(self, file_paths):
        """加载文档并处理"""
        documents = []

        for file_path in file_paths:
            try:
                if file_path.endswith('.pdf'):
                    loader = PyPDFLoader(file_path)
                    docs = loader.load()
                    documents.extend(docs)
                    print(f"已加载PDF文档: {file_path}, 共{len(docs)}页")
                elif file_path.endswith('.txt'):
                    loader = TextLoader(file_path, encoding='utf-8')
                    docs = loader.load()
                    documents.extend(docs)
                    print(f"已加载文本文件: {file_path}")
                else:
                    print(f"不支持的文件格式: {file_path}")
            except Exception as e:
                print(f"加载文档{file_path}时出错: {str(e)}")

        if not documents:
            print("没有加载到任何文档")
            return

        # 分割文档为小块（针对中文优化）
        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=300,
            chunk_overlap=50,
            separators=["。", "！", "？", "；", "，", " ", ""]
        )
        splits = text_splitter.split_documents(documents)

        # 过滤空文本块
        splits = [doc for doc in splits if doc.page_content.strip() and len(doc.page_content.strip()) > 10]
        if not splits:
            print("错误：所有文本块为空，无法构建知识库")
            return
        print(f"文档分割完成，共{len(splits)}个有效文本块")

        # 测试Embedding模型
        try:
            test_embedding = self.embeddings.embed_query(splits[0].page_content)
            if not test_embedding:
                print("错误：Embedding模型无法生成向量")
                return
        except Exception as e:
            print(f"Embedding模型错误: {e}")
            return

        # 创建FAISS向量数据库
        self.vector_db = FAISS.from_documents(
            documents=splits,
            embedding=self.embeddings
        )

        # 保存FAISS数据库到本地
        self.vector_db.save_local(self.persist_directory)
        print(f"知识库已创建并保存到 {self.persist_directory}")

        # 初始化问答链
        self._init_qa_chain()

    def _init_qa_chain(self):
        """初始化基于千问模型的问答链"""
        # 定义中文提示词模板
        prompt_template = """你是一个基于提供的文档内容进行回答的助手。
请严格根据以下上下文信息回答用户的问题，确保答案准确、简洁。
如果上下文信息不足以回答问题，请直接说明"根据提供的文档，我无法回答这个问题"，不要编造答案。

上下文:
{context}

问题:
{question}

回答:
"""
        prompt = PromptTemplate(
            template=prompt_template,
            input_variables=["context", "question"]
        )

        # 配置量化参数
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.bfloat16
        )

        # 加载千问模型（使用较小的模型确保在Colab中运行）
        model_name_or_path = "Qwen/Qwen3-1.7B"  # 更小的模型，适合Colab

        # 加载tokenizer
        tokenizer = AutoTokenizer.from_pretrained(
            model_name_or_path,
            trust_remote_code=True
        )

        # 加载模型
        model = AutoModelForCausalLM.from_pretrained(
            model_name_or_path,
            quantization_config=bnb_config,
            device_map="auto",
            trust_remote_code=True,
            low_cpu_mem_usage=True
        )
        model.eval()

        # 测试模型是否正常
        try:
            test_input = tokenizer("你好", return_tensors="pt").to(self.device)
            test_output = model.generate(**test_input, max_new_tokens=10)
            print(f"模型测试: {tokenizer.decode(test_output[0], skip_special_tokens=True)}")
        except Exception as e:
            print(f"模型加载失败: {e}")
            return

        # 创建文本生成管道
        pipe = pipeline(
            "text-generation",
            model=model,
            tokenizer=tokenizer,
            max_new_tokens=512,
            temperature=0.1,
            top_p=0.9,
            repetition_penalty=1.1
        )

        # 将HuggingFace管道包装为LangChain的LLM
        llm = HuggingFacePipeline(pipeline=pipe)

        # 创建检索式问答链
        self.qa_chain = RetrievalQA.from_chain_type(
            llm=llm,
            chain_type="stuff",
            retriever=self.vector_db.as_retriever(
                search_kwargs={"k": 4}
            ),
            chain_type_kwargs={"prompt": prompt},
            return_source_documents=True
        )

    def ask_question(self, question):
        """向知识库提问"""
        if not self.qa_chain:
            return "请先上传文档构建知识库"

        try:
            # 使用invoke方法替代__call__，避免 deprecation warning
            result = self.qa_chain.invoke({"query": question})

            # 整理回答和来源
            answer = f"问题: {question}\n\n回答: {result['result']}\n\n"

            answer += "信息来源:\n"
            sources = set()
            for doc in result['source_documents']:
                source = doc.metadata.get('source', '未知')
                page = doc.metadata.get('page', '未知')
                sources.add(f"- 文档: {os.path.basename(source)}, 页面: {page}")

            answer += "\n".join(sources)
            return answer
        except Exception as e:
            return f"回答问题时出错: {str(e)}"

# 5. 初始化知识库
kb = QwenFAISSKnowledgeBase()

# 6. 上传文档
kb.upload_documents()

# 7. 交互式问答
print("--- 个人知识库问答工具 ---")
print("输入问题进行查询，输入'q'退出")

while True:
    question = input("\n请输入问题: ")
    if question.lower() == 'q':
        break
    response = kb.ask_question(question)
    print("\n" + response)

